library-path="/home/ilan/Programs/native_client_deepspeech/libdeepspeech.so"
model-path = "/home/ilan/Programs/native_client_deepspeech/deepspeech-0.7.4-models.pbmm"
#scorer-path = "/home/ilan/Downloads/deepspeech-0.7.4-models.scorer"

[[commands]]
message = "tee tee"
command = "firefox https://tenno.tools/ns"

[[commands]]
message = "why tee"
command = "firefox youtube.com"

[[commands]]
message = "fire fox"
command = "firefox"