library-path="/home/ilan/Programs/native_client_deepspeech/libdeepspeech.so"
model-path = "/home/ilan/Programs/native_client_deepspeech/deepspeech-0.7.4-models.pbmm"
#scorer-path = "/home/ilan/Downloads/deepspeech-0.7.4-models.scorer"

[[command]]
message = "firefox"
mode = "firefox"

[[command]]
message = "h top"
command = "alacritty -c htop"

[[mode]]
name = "firefox"

[[mode.command]]
message = "youtube"
command = "firefox youtube.com"

[[mode.command]]
message = "tee tee"
command = "firefox https://tenno.tools/ns"